apiVersion: v1
entries:
  grafana-agent-operator:
  - apiVersion: v2
    appVersion: 0.25.1
    created: "2022-12-27T13:57:46.744111772Z"
    description: A Helm chart for Grafana Agent Operator
    digest: 0a00fdc2dc77f73ad818b4ba100207b9743b8610a0ab1b4c54ef6c29dbdd15c5
    home: https://grafana.com/docs/agent/latest/
    icon: https://raw.githubusercontent.com/grafana/agent/v0.25.1/docs/assets/logo_and_name.png
    maintainers:
    - email: grafana-agent-team@googlegroups.com
      name: Grafana Agent Team
    name: grafana-agent-operator
    sources:
    - https://github.com/grafana/agent/tree/v0.25.1/pkg/operator
    type: application
    urls:
    - charts/grafana-agent-operator-0.2.2.tgz
    version: 0.2.2
  minio:
  - apiVersion: v1
    appVersion: master
    created: "2022-12-27T13:57:46.758624944Z"
    description: High Performance, Kubernetes Native Object Storage
    digest: 6fbf8a38939ad826e669b7a0a2b53d05310eddf91a115585aa481b48ffe982de
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - storage
    - object-storage
    - S3
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: minio
    sources:
    - https://github.com/minio/minio
    urls:
    - charts/minio-8.0.9.tgz
    version: 8.0.9
  tempo-distributed:
  - apiVersion: v2
    appVersion: 1.5.0
    created: "2022-12-27T13:57:46.739262666Z"
    dependencies:
    - alias: minio
      condition: minio.enabled
      name: minio
      repository: https://helm.min.io/
      version: 8.0.9
    - alias: grafana-agent-operator
      condition: metaMonitoring.grafanaAgent.installOperator
      name: grafana-agent-operator
      repository: https://grafana.github.io/helm-charts
      version: 0.2.2
    description: Grafana Tempo in MicroService mode
    digest: 08fa4b46facc19aeeeb0b99f928bdc669ab1a7ecd4057ff454400f2c167fc5ab
    home: https://grafana.com/docs/tempo/latest/
    icon: https://raw.githubusercontent.com/grafana/tempo/master/docs/tempo/website/logo_and_name.png
    maintainers:
    - email: number101010@gmail.com
      name: joe-elliott
    - email: 9215868@gmail.com
      name: swartz-k
    - name: annanay25
    - name: mdisibio
    - name: mapno
    - name: BitProcessor
    - name: faustodavid
    - name: zalegrala
    name: tempo-distributed
    sources:
    - https://github.com/grafana/tempo
    type: application
    urls:
    - tempo-distributed-0.27.15.tgz
    version: 0.27.15
generated: "2022-12-27T13:57:46.696296761Z"
